import assert from "node:assert/strict";
import { access, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { setTimeout as delay } from "node:timers/promises";
import { join } from "node:path";
import test from "node:test";
import { compactEntries, computeGenerationHash, resolveCompactorConfig } from "../src/compactor.js";
import { runCompactionWorker } from "../src/compaction-worker-client.js";
import { validateWorkerRequest, validateWorkerResponse, type ReplayWorkerRequest, type WorkerSourceExpectation } from "../src/compaction-worker-protocol.js";
import { getActiveBranch, getSourceEntriesBefore, parseSessionJsonl } from "../src/jsonl.js";
import { buildDeterministicSummaryRebase } from "../src/summary-rebase.js";
import { parseHistoricalBlocks } from "../src/blocks.js";
import { renderHybridCompaction } from "../src/pi-hybrid.js";
import { estimateTokensFromText } from "../src/utils.js";

function entries(tasks=8): Record<string, unknown>[] {
  const output: Record<string, unknown>[]=[{type:"message",id:"root",parentId:null,message:{role:"user",content:"Keep immutable JSONL. The release remains blocked until approval."}}];let parent="root";
  for(let n=1;n<=tasks;n++){const a=`a${n}`,r=`r${n}`,f=`f${n}`,call=`c${n}`;output.push({type:"message",id:a,parentId:parent,message:{role:"assistant",content:[{type:"toolCall",id:call,name:"read",arguments:{path:"/repo/a.ts",revision:n}}],stopReason:"toolUse"}});output.push({type:"message",id:r,parentId:a,message:{role:"toolResult",toolCallId:call,toolName:"read",content:[{type:"text",text:`revision=${n}\n${Array.from({length:70},(_,i)=>`export const stable${i}=${i};`).join("\n")}`}],isError:false,details:{exitCode:0}}});output.push({type:"message",id:f,parentId:r,message:{role:"assistant",content:[{type:"text",text:`Revision ${n} observed; later work can supersede it.`}],stopReason:"stop"}});parent=f;}return output;
}
async function fixture(tasks=8){const directory=await mkdtemp(join(tmpdir(),"chrono-worker-test-"));const sessionPath=join(directory,"session.jsonl");const values=entries(tasks);await writeFile(sessionPath,`${JSON.stringify({type:"session",version:3,id:"test"})}\n${values.map((entry)=>JSON.stringify(entry)).join("\n")}\n`,{mode:0o600});const value=await stat(sessionPath);const expectedSource:WorkerSourceExpectation={deviceId:String(value.dev),inodeId:String(value.ino),size:value.size,mtimeMs:value.mtimeMs};const config=resolveCompactorConfig({targetTokens:4_000,enableSemanticCompression:false});const request:ReplayWorkerRequest={schemaVersion:1,jobId:"replay-1",jobType:"replay-compaction",sessionPath,expectedSource,deadlineMs:Date.now()+60_000,niceLevel:10,branchLeafId:`f${tasks}`,firstKeptEntryId:`f${tasks}`,config,hardOutputTokens:25_000,retentionHints:"",pinnedMemoryText:"",candidateStoreEnabled:false,cacheEnabled:false};return{directory,sessionPath,request};}
async function waitForMarker(marker:string,timeoutMs=3_000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){try{await access(marker);return;}catch{}await delay(10);}throw new Error("synthetic worker readiness timeout");}

test("worker protocol rejects unknown, missing, invalid, and oversized request fields",async()=>{const value=await fixture();try{assert.equal(validateWorkerRequest(value.request).jobType,"replay-compaction");for(const changed of [{...value.request,unknown:true},{...value.request,niceLevel:20},{...value.request,deadlineMs:Date.now()+4_000_000},{...value.request,retentionHints:"x".repeat(600_000)},{...value.request,config:{...value.request.config,unknown:1}}])assert.throws(()=>validateWorkerRequest(changed),/worker-protocol-error/);}finally{await rm(value.directory,{recursive:true,force:true});}});

test("response validation is strict and binds the job",()=>{const metrics={workerPid:1,totalWallMs:1,compactionMs:0,cpuUserMicros:1,cpuSystemMicros:1,peakRssKiB:1,priorityApplied:false,cacheState:"disabled",modelCalls:0,networkCalls:0,secretSentinelPresent:false,sourceLedgerTransition:"exact-hit",ledgerColdLoadMs:0,branchResolveMs:0,branchReadMs:0,branchEntryCount:0,branchSourceBytes:0,sourceRangeCount:0,sourceBytesRead:0,sourceByteAvoidanceRate:0,completeSessionReadAvoided:true,candidateLedgerReused:false};const failed={schemaVersion:1,jobId:"x",status:"failed",jobType:"replay-compaction",failureCode:"invalid-cut",metrics} as const;assert.equal(validateWorkerResponse(failed,"x").status,"failed");assert.throws(()=>validateWorkerResponse({...failed,extra:1},"x"));assert.throws(()=>validateWorkerResponse({...failed,failureCode:"raw-path"},"x"));assert.throws(()=>validateWorkerResponse(failed,"other"));});

test("child reconstructs the exact persisted branch and matches in-process replay bytes",async()=>{const value=await fixture();try{const run=await runCompactionWorker(value.request,{schedulerDirectory:join(value.directory,"scheduler"),workerTimeoutMs:60_000});assert.equal(run.response.status,"ok");if(run.response.status!=="ok"||!run.response.replay)return;const parsed=parseSessionJsonl(await readFile(value.sessionPath,"utf8"));const branch=getActiveBranch(parsed,value.request.branchLeafId);const source=getSourceEntriesBefore(branch,value.request.firstKeptEntryId);const future=branch.slice(branch.findIndex(x=>x.id===value.request.firstKeptEntryId));const expected=await compactEntries(source,{config:value.request.config,hardOutputTokens:value.request.hardOutputTokens,futureEntries:future});assert.equal(run.response.replay.summary,expected.summary);assert.equal(run.response.replay.generationHash,expected.details.generationHash);assert.equal(typeof computeGenerationHash(source,value.request.config,"",future,""),"string");assert.deepEqual(run.response.replay.validation,expected.validation);assert.deepEqual(run.response.replay.planSources,expected.plan.units.map(x=>({unitId:x.id,sourceRefs:x.sourceRefs})));assert.ok(run.clientMetrics.mainProcessMaximumTimerDelayMs<250);assert.equal(run.response.metrics.modelCalls,0);assert.equal(run.response.metrics.networkCalls,0);const altered=structuredClone(run.response) as unknown as {replay:Record<string,unknown>};altered.replay.unexpected="must reject";assert.throws(()=>validateWorkerResponse(altered,value.request.jobId));}finally{await rm(value.directory,{recursive:true,force:true});}});

test("worker equality matrix matches 19 deterministic replay scenarios",async()=>{const value=await fixture(20);try{const parsed=parseSessionJsonl(await readFile(value.sessionPath,"utf8")),branch=getActiveBranch(parsed,value.request.branchLeafId);for(let scenario=1;scenario<=19;scenario++){const firstKeptEntryId=`f${scenario+1}`,source=getSourceEntriesBefore(branch,firstKeptEntryId),future=branch.slice(branch.findIndex(x=>x.id===firstKeptEntryId)),config=resolveCompactorConfig({...value.request.config,targetTokens:3_500+(scenario%4)*125}),retentionHints=scenario%3===0?`Keep scenario ${scenario} unresolved.`:"",expected=await compactEntries(source,{config,hardOutputTokens:25_000,futureEntries:future,retentionHints}),run=await runCompactionWorker({...value.request,jobId:`matrix-${scenario}`,firstKeptEntryId,config,retentionHints},{schedulerDirectory:join(value.directory,"scheduler")});assert.equal(run.response.status,"ok",`scenario ${scenario}`);if(run.response.status!=="ok"||!run.response.replay)continue;assert.equal(run.response.replay.summary,expected.summary);assert.equal(run.response.replay.renderedTokens,expected.renderedTokens);assert.equal(run.response.replay.generationHash,expected.details.generationHash);assert.deepEqual(run.response.replay.validation,expected.validation);assert.deepEqual(run.response.replay.planSources,expected.plan.units.map(x=>({unitId:x.id,sourceRefs:x.sourceRefs})));}}finally{await rm(value.directory,{recursive:true,force:true});}});

test("selected leaf excludes an abandoned branch and reports the exact cut prefix",async()=>{const value=await fixture();try{const original=await readFile(value.sessionPath,"utf8"),alternative={type:"message",id:"alt",parentId:"f4",message:{role:"user",content:"Alternative branch remains unresolved."}},tail={type:"message",id:"alt-tail",parentId:"alt",message:{role:"assistant",content:[{type:"text",text:"Continue alternative branch."}],stopReason:"stop"}};await writeFile(value.sessionPath,`${original}${JSON.stringify(alternative)}\n${JSON.stringify(tail)}\n`);const s=await stat(value.sessionPath),request={...value.request,jobId:"alternative",branchLeafId:"alt-tail",firstKeptEntryId:"alt-tail",expectedSource:{deviceId:String(s.dev),inodeId:String(s.ino),size:s.size,mtimeMs:s.mtimeMs}};const run=await runCompactionWorker(request,{schedulerDirectory:join(value.directory,"scheduler")});assert.equal(run.response.status,"ok");if(run.response.status==="ok"&&run.response.replay){assert.equal(run.response.replay.sourceEntryCount,14);assert.doesNotMatch(run.response.replay.summary,/Revision 8 observed/);}}finally{await rm(value.directory,{recursive:true,force:true});}});

test("deterministic summary rebase and replay budgeting remain byte-identical in the child",async()=>{const value=await fixture();try{const request={...value.request,jobId:"rebase",deterministicRebase:{targetTokens:1_000,combinedTargetTokens:4_000,historicalCeilingTokens:25_000}};const run=await runCompactionWorker(request,{schedulerDirectory:join(value.directory,"scheduler")});assert.equal(run.response.status,"ok");if(run.response.status!=="ok"||!run.response.replay)return;const branch=getActiveBranch(parseSessionJsonl(await readFile(value.sessionPath,"utf8")),request.branchLeafId),source=getSourceEntriesBefore(branch,request.firstKeptEntryId),future=branch.slice(branch.findIndex(x=>x.id===request.firstKeptEntryId));const rebase=buildDeterministicSummaryRebase(parseHistoricalBlocks(source,{includeHistoricalCompactions:false,includeMetadata:false}),undefined,1_000),rebaseTokens=estimateTokensFromText(rebase),wrapper=Math.max(0,estimateTokensFromText(renderHybridCompaction(rebase,""))-rebaseTokens),target=Math.min(25_000-rebaseTokens-wrapper,Math.max(256,4_000-rebaseTokens-wrapper)),expected=await compactEntries(source,{config:resolveCompactorConfig({...request.config,targetTokens:target}),hardOutputTokens:25_000-rebaseTokens-wrapper,futureEntries:future});assert.equal(run.response.replay.deterministicRebaseText,rebase);assert.equal(run.response.replay.summary,expected.summary);assert.equal(run.response.replay.generationHash,expected.details.generationHash);}finally{await rm(value.directory,{recursive:true,force:true});}});

test("child environment excludes credentials and timeout, crash, and abort return safe codes",async()=>{const value=await fixture(2);const old=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY="must-not-cross";try{const entry=join(value.directory,"probe.mjs");await writeFile(entry,`process.on("message",q=>process.send({schemaVersion:1,jobId:q.jobId,status:"failed",jobType:q.jobType,failureCode:"worker-disabled",metrics:{workerPid:process.pid,totalWallMs:0,compactionMs:0,cpuUserMicros:0,cpuSystemMicros:0,peakRssKiB:0,priorityApplied:false,cacheState:"disabled",modelCalls:0,networkCalls:0,secretSentinelPresent:Boolean(process.env.OPENAI_API_KEY),sourceLedgerTransition:"exact-hit",ledgerColdLoadMs:0,branchResolveMs:0,branchReadMs:0,branchEntryCount:0,branchSourceBytes:0,sourceRangeCount:0,sourceBytesRead:0,sourceByteAvoidanceRate:0,completeSessionReadAvoided:true,candidateLedgerReused:false}}));`);const probe=await runCompactionWorker({...value.request,jobId:"probe"},{entryPath:entry,schedulerDirectory:join(value.directory,"probe-scheduler")});assert.equal(probe.response.status,"failed");if(probe.response.status==="failed")assert.equal(probe.response.failureCode,"worker-disabled");const waitEntry=join(value.directory,"wait.mjs"),readyMarker=`${value.sessionPath}.chrono-ready`;await writeFile(waitEntry,`import { writeFileSync } from "node:fs";process.on("message",q=>{writeFileSync(q.sessionPath+".chrono-ready","ready",{mode:0o600});setTimeout(()=>{},60000);});`);const timedPromise=runCompactionWorker({...value.request,jobId:"timeout"},{entryPath:waitEntry,workerTimeoutMs:500,schedulerDirectory:join(value.directory,"timeout-scheduler")});await waitForMarker(readyMarker);const timed=await timedPromise;await rm(readyMarker,{force:true});assert.equal(timed.response.status,"failed");if(timed.response.status==="failed")assert.equal(timed.response.failureCode,"worker-timeout");const controller=new AbortController(),abortedPromise=runCompactionWorker({...value.request,jobId:"abort"},{entryPath:waitEntry,workerTimeoutMs:15_000,signal:controller.signal,schedulerDirectory:join(value.directory,"abort-scheduler")});await waitForMarker(readyMarker);controller.abort();const aborted=await abortedPromise;await rm(readyMarker,{force:true});assert.equal(aborted.response.status,"failed");if(aborted.response.status==="failed")assert.equal(aborted.response.failureCode,"worker-aborted");const crashEntry=join(value.directory,"crash.mjs");await writeFile(crashEntry,"process.exit(2);\n");const crashed=await runCompactionWorker({...value.request,jobId:"crash"},{entryPath:crashEntry,schedulerDirectory:join(value.directory,"crash-scheduler")});assert.equal(crashed.response.status,"failed");if(crashed.response.status==="failed")assert.equal(crashed.response.failureCode,"worker-crashed");}finally{if(old===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=old;await rm(value.directory,{recursive:true,force:true});}});

test("branch, cut, source stability, cache, and candidate update failures are safe",async()=>{const value=await fixture();try{for(const [patch,code] of [[{branchLeafId:"missing"},"branch-not-persisted"],[{firstKeptEntryId:"missing"},"invalid-cut"],[{expectedSource:{...value.request.expectedSource,size:value.request.expectedSource.size+1}},"source-changed"]] as const){const run=await runCompactionWorker({...value.request,...patch,jobId:`job-${code}`},{schedulerDirectory:join(value.directory,code),workerTimeoutMs:60_000});assert.equal(run.response.status,"failed");if(run.response.status==="failed")assert.equal(run.response.failureCode,code);}const first=await runCompactionWorker({...value.request,jobId:"cache-1",cacheEnabled:true},{schedulerDirectory:join(value.directory,"cache")});const second=await runCompactionWorker({...value.request,jobId:"cache-2",cacheEnabled:true},{schedulerDirectory:join(value.directory,"cache")});assert.equal(first.response.status,"ok");assert.equal(second.response.metrics.cacheState,"hit");const reused=await runCompactionWorker({...value.request,jobId:"candidate-ledger-reuse",candidateStoreEnabled:true},{schedulerDirectory:join(value.directory,"cache")});assert.equal(reused.response.status,"ok");assert.equal(reused.response.metrics.candidateLedgerReused,true);assert.equal(reused.response.metrics.completeSessionReadAvoided,true);await writeFile(`${value.sessionPath}.chrono-worker-replay-v1.json`,JSON.stringify({schemaVersion:1,key:"forged",payloadHash:"forged",result:{summary:"forged"}}));const damaged=await runCompactionWorker({...value.request,jobId:"cache-3",cacheEnabled:true},{schedulerDirectory:join(value.directory,"cache")});assert.equal(damaged.response.status,"ok");assert.equal(damaged.response.metrics.cacheState,"miss");const update=await runCompactionWorker({schemaVersion:1,jobId:"update",jobType:"candidate-store-update",sessionPath:value.sessionPath,expectedSource:value.request.expectedSource,deadlineMs:Date.now()+60_000,niceLevel:10,config:value.request.config},{schedulerDirectory:join(value.directory,"update"),workerTimeoutMs:60_000});assert.equal(update.response.status,"ok");assert.equal(update.response.jobType,"candidate-store-update");}finally{await rm(value.directory,{recursive:true,force:true});}});
