import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { acquireHostWorkerSlot, linuxProcessStartIdentity, schedulerArtifactCounts } from "../src/host-worker-scheduler.js";

async function directory(){return mkdtemp(join(tmpdir(),"chrono-scheduler-test-"));}
const options=(path:string,slots:number,priority:"high"|"low"="high",signal?:AbortSignal)=>({directory:path,slots,priority,signal,jobType:priority==="high"?"replay-compaction" as const:"candidate-store-update" as const,timeoutMs:3_000,pollMs:20});
function waitForReady(promise:Promise<void>,timeoutMs=5_000){return new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("scheduler readiness timeout")),timeoutMs);promise.then(()=>{clearTimeout(timer);resolve();},error=>{clearTimeout(timer);reject(error);});});}

test("scheduler enforces one, two, and four host slots without residue",async()=>{for(const slots of [1,2,4]){const path=await directory();let releaseHeld=()=>{};try{let active=0,maximum=0,acquired=0;let releaseReady!:()=>void;const held=new Promise<void>(resolve=>{releaseHeld=resolve;}),ready=new Promise<void>(resolve=>{releaseReady=resolve;});const workers=Array.from({length:slots+1},async()=>{const lease=await acquireHostWorkerSlot(options(path,slots));active++;maximum=Math.max(maximum,active);acquired++;if(acquired===slots)releaseReady();await held;active--;await lease.release();});try{await waitForReady(ready);assert.equal(maximum,slots);}finally{releaseHeld();const settled=await Promise.allSettled(workers);assert.ok(settled.every(result=>result.status==="fulfilled"),"scheduler worker did not settle cleanly");}assert.equal(active,0);assert.deepEqual(await schedulerArtifactCounts(path),{tickets:0,slots:0});}finally{releaseHeld();await rm(path,{recursive:true,force:true});}}});

test("waiting replay work has priority over a waiting candidate update",async()=>{const path=await directory();try{const held=await acquireHostWorkerSlot(options(path,1));const order:string[]=[];const low=acquireHostWorkerSlot(options(path,1,"low")).then(async lease=>{order.push("low");await lease.release();});await new Promise(resolve=>setTimeout(resolve,25));const high=acquireHostWorkerSlot(options(path,1,"high")).then(async lease=>{order.push("high");await lease.release();});await new Promise(resolve=>setTimeout(resolve,25));await held.release();await Promise.all([low,high]);assert.deepEqual(order,["high","low"]);}finally{await rm(path,{recursive:true,force:true});}});

test("scheduler cancellation, timeout, dead owner recovery, and live owner safety are bounded",async()=>{const path=await directory();try{const held=await acquireHostWorkerSlot(options(path,1));const controller=new AbortController();const cancelled=acquireHostWorkerSlot(options(path,1,"high",controller.signal));setTimeout(()=>controller.abort(),25);await assert.rejects(cancelled,/worker-aborted/);await assert.rejects(acquireHostWorkerSlot({...options(path,1),timeoutMs:40}),/scheduler-timeout/);await held.release();const dead={schemaVersion:1,pid:99999999,processStartIdentity:"1",nonce:"dead",createdAtMs:Date.now(),priority:"low",jobType:"candidate-store-update"};await writeFile(join(path,"slot-0.json"),JSON.stringify(dead),{mode:0o600});const recovered=await acquireHostWorkerSlot(options(path,1));await recovered.release();const live={...dead,pid:process.pid,processStartIdentity:linuxProcessStartIdentity()!,nonce:"live"};await writeFile(join(path,"slot-0.json"),JSON.stringify(live),{mode:0o600});await assert.rejects(acquireHostWorkerSlot({...options(path,1),timeoutMs:40}),/scheduler-timeout/);assert.equal(JSON.parse(await readFile(join(path,"slot-0.json"),"utf8")).nonce,"live");}finally{await rm(path,{recursive:true,force:true});}});

test("lease release never removes a replacement owner",async()=>{const path=await directory();try{const lease=await acquireHostWorkerSlot(options(path,1));const slot=join(path,"slot-0.json"),owner=JSON.parse(await readFile(slot,"utf8"));await writeFile(slot,JSON.stringify({...owner,nonce:"replacement"}),{mode:0o600});await lease.release();assert.equal(JSON.parse(await readFile(slot,"utf8")).nonce,"replacement");await rm(slot,{force:true});}finally{await rm(path,{recursive:true,force:true});}});

test("scheduler artifacts contain only bounded ownership data and no source paths",async()=>{const path=await directory();try{const lease=await acquireHostWorkerSlot(options(path,1));for(const name of await readdir(path)){const text=await readFile(join(path,name),"utf8");assert.doesNotMatch(text,/session|project|source|\.jsonl|\/home\//i);assert.ok(text.length<1_000);}await lease.release();}finally{await rm(path,{recursive:true,force:true});}});
