import assert from "node:assert/strict";
import { appendFile, mkdtemp, open, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { coalesceSourceLedgerRanges, LedgerBranchError, loadSourceLedgerBranch, readSourceLedgerEntries, resolveSourceLedgerBranch, splitLedgerBranchAtEntry } from "../src/ledger-branch.js";
import { updateSourceLedger, type SourceLedger } from "../src/source-ledger.js";

const header={type:"session",version:3,id:"ledger-branch-test"};
const entry=(id:string,parentId:string|null,text=`text-${id}`)=>({type:"message",id,parentId,message:{role:"user",content:text}});
async function fixture(t:test.TestContext, values:readonly Record<string,unknown>[], ending="\n") { const directory=await mkdtemp(join(tmpdir(),"chrono-ledger-branch-"));t.after(()=>rm(directory,{recursive:true,force:true}));const sessionPath=join(directory,"session.jsonl");await writeFile(sessionPath,[header,...values].map(value=>JSON.stringify(value)).join(ending)+ending,{mode:0o600});return{directory,sessionPath,ledger:await updateSourceLedger(sessionPath)}; }
function changed(ledger:SourceLedger, sourceOrder=ledger.sourceOrder):SourceLedger{return{...ledger,sourceOrder,entryById:new Map(sourceOrder.map(value=>[value.entryId,value]))};}
async function afterNextPositionalRead(path:string,position:number,action:()=>Promise<void>):Promise<{restore:()=>void;called:()=>boolean}>{const probe=await open(path,"r");const prototype=Object.getPrototypeOf(probe) as {read:(...args:unknown[])=>Promise<unknown>};await probe.close();const original=prototype.read;let intercepted=false;prototype.read=async function(...args:unknown[]):Promise<unknown>{const result=await original.apply(this,args);if(!intercepted&&args[3]===position){intercepted=true;await action();}return result;};return{restore:()=>{prototype.read=original;},called:()=>intercepted};}

test("resolves exact nested and abandoned branches and preserves the exact cut",async t=>{const f=await fixture(t,[entry("a",null),entry("b","a"),entry("abandoned","a"),entry("c","b"),entry("d","c")]);const branch=resolveSourceLedgerBranch(f.ledger,"d").entries;assert.deepEqual(branch.map(x=>x.entryId),["a","b","c","d"]);assert.deepEqual(splitLedgerBranchAtEntry(branch,"c"),{source:branch.slice(0,2),future:branch.slice(2),cutIndex:2});assert.deepEqual((await loadSourceLedgerBranch(f.sessionPath,f.ledger,"d")).entries.map(x=>x.id),["a","b","c","d"]);assert.throws(()=>resolveSourceLedgerBranch(f.ledger,"missing"),(error:unknown)=>error instanceof LedgerBranchError&&error.code==="branch-not-persisted");assert.throws(()=>splitLedgerBranchAtEntry(branch,"abandoned"),(error:unknown)=>error instanceof LedgerBranchError&&error.code==="invalid-cut");});

test("parent defects, cycles, duplicates, and source-order reversals fail closed",async t=>{const f=await fixture(t,[entry("a",null),entry("b","a"),entry("c","b")]);const [a,b,c]=f.ledger.sourceOrder;assert.throws(()=>resolveSourceLedgerBranch(changed(f.ledger,[a!,{...b!,parentId:"missing"},c!]),"b"),(e:unknown)=>e instanceof LedgerBranchError&&e.code==="branch-parent-missing");assert.throws(()=>resolveSourceLedgerBranch(changed(f.ledger,[{...a!,parentId:"b"},b!,c!]),"b"),(e:unknown)=>e instanceof LedgerBranchError&&e.code==="branch-cycle");assert.throws(()=>resolveSourceLedgerBranch(changed(f.ledger,[b!,a!,c!]),"b"),(e:unknown)=>e instanceof LedgerBranchError&&e.code==="branch-source-order");assert.throws(()=>resolveSourceLedgerBranch(changed(f.ledger,[a!,b!,{...c!,entryId:"b"}]),"b"),(e:unknown)=>e instanceof LedgerBranchError&&e.code==="branch-cycle");});

test("coalesces bounded ranges without splitting an oversized entry",async t=>{const f=await fixture(t,[entry("a",null,"x".repeat(100)),entry("b","a","y".repeat(100)),entry("c","b","z".repeat(100))]);const values=f.ledger.sourceOrder;assert.equal(coalesceSourceLedgerRanges(values,{maximumGapBytes:1000,maximumRangeBytes:1_000_000,maximumEntriesPerRange:2}).length,2);assert.equal(coalesceSourceLedgerRanges(values,{maximumGapBytes:0,maximumRangeBytes:1_000_000,maximumEntriesPerRange:10}).length,3);const huge={...values[0]!,sourceByteLength:5_000_000};const range=coalesceSourceLedgerRanges([huge],{maximumRangeBytes:10});assert.equal(range.length,1);assert.equal(range[0]!.endByte-range[0]!.startByte,5_000_000);});

test("reads only selected verified ranges and reports avoidance",async t=>{const f=await fixture(t,[entry("a",null),entry("x",null,"abandoned".repeat(1000)),entry("b","a")]);const selected=[f.ledger.entryById.get("a")!,f.ledger.entryById.get("b")!];const loaded=await readSourceLedgerEntries(f.sessionPath,f.ledger,selected,{maximumGapBytes:0});assert.deepEqual(loaded.entries.map(x=>x.id),["a","b"]);assert.equal(loaded.metrics.sourceRangeCount,2);assert.equal(loaded.metrics.totalSourceBytesRead,loaded.metrics.selectedSourceBytes);assert.ok(loaded.metrics.sourceByteAvoidanceRate>0.8);const bytes=await readFile(f.sessionPath);const position=selected[1]!.sourceByteOffset;bytes[position+5]=bytes[position+5]!^1;await writeFile(f.sessionPath,bytes);await assert.rejects(()=>readSourceLedgerEntries(f.sessionPath,f.ledger,[selected[1]!]),(e:unknown)=>e instanceof LedgerBranchError&&e.code==="source-changed");});

test("supports CRLF, UTF-8, and one selected oversized entry",async t=>{const f=await fixture(t,[entry("a",null,"雪"),entry("b","a","x".repeat(2_000_000))],"\r\n");const loaded=await loadSourceLedgerBranch(f.sessionPath,f.ledger,"b",{maximumRangeBytes:1024});assert.equal(loaded.entries[0]!.message&&JSON.stringify(loaded.entries[0]!.message).includes("雪"),true);assert.equal(loaded.metrics.sourceRangeCount,2);assert.ok(loaded.metrics.maximumEntryBytes>1_000_000);assert.equal((await stat(f.sessionPath)).size,loaded.metrics.sourceFileBytes);});

test("accepts genuine appends before and during verified range reads",async t=>{const f=await fixture(t,[entry("a",null),entry("tail","a","x".repeat(4_000))]);const selected=[f.ledger.entryById.get("a")!];await appendFile(f.sessionPath,`${JSON.stringify(entry("later","tail"))}\n`);assert.deepEqual((await readSourceLedgerEntries(f.sessionPath,f.ledger,selected)).entries.map(value=>value.id),["a"]);const hook=await afterNextPositionalRead(f.sessionPath,f.ledger.checkpoint.anchorSourceOffset,()=>appendFile(f.sessionPath,`${JSON.stringify(entry("during","later"))}\n`));try{assert.deepEqual((await readSourceLedgerEntries(f.sessionPath,f.ledger,selected)).entries.map(value=>value.id),["a"]);assert.equal(hook.called(),true);}finally{hook.restore();}});

test("fails closed for replacement, truncation, checkpoint mutation, and selected mutation",async t=>{const make=async(name:string)=>{const f=await fixture(t,[entry("a",null,"selected"),entry("tail","a","x".repeat(4_000))]);const path=join(f.directory,`${name}.jsonl`);await rename(f.sessionPath,path);return{...f,sessionPath:path};};const replaced=await make("replaced");const replacement=join(replaced.directory,"replacement-new.jsonl");await writeFile(replacement,await readFile(replaced.sessionPath));await rename(replacement,replaced.sessionPath);await assert.rejects(()=>readSourceLedgerEntries(replaced.sessionPath,replaced.ledger,[replaced.ledger.sourceOrder[0]!]));const truncated=await make("truncated");await writeFile(truncated.sessionPath,(await readFile(truncated.sessionPath)).subarray(0,truncated.ledger.checkpoint.sourceFileSize-1));await assert.rejects(()=>readSourceLedgerEntries(truncated.sessionPath,truncated.ledger,[truncated.ledger.sourceOrder[0]!]));for(const [name,offset] of [["checkpoint",(ledger:SourceLedger)=>ledger.checkpoint.anchorSourceOffset],["selected",(ledger:SourceLedger)=>ledger.sourceOrder[0]!.sourceByteOffset+10]] as const){const f=await make(name);const bytes=await readFile(f.sessionPath);const index=offset(f.ledger);bytes[index]=bytes[index]!^1;await writeFile(f.sessionPath,bytes);await assert.rejects(()=>readSourceLedgerEntries(f.sessionPath,f.ledger,[f.ledger.sourceOrder[0]!]));}});

test("revalidates the checkpoint anchor after selected range reads",async t=>{const f=await fixture(t,[entry("a",null),entry("tail","a","x".repeat(4_000))]);const selected=f.ledger.sourceOrder[0]!;const hook=await afterNextPositionalRead(f.sessionPath,selected.sourceByteOffset,async()=>{const bytes=await readFile(f.sessionPath);const index=f.ledger.checkpoint.anchorSourceOffset;bytes[index]=bytes[index]!^1;await writeFile(f.sessionPath,bytes);});try{await assert.rejects(()=>readSourceLedgerEntries(f.sessionPath,f.ledger,[selected]),(error:unknown)=>error instanceof LedgerBranchError&&error.code==="source-changed");assert.equal(hook.called(),true);}finally{hook.restore();}});
