import test from "node:test";
import assert from "node:assert/strict";
import { compactEntries, resolveCompactorConfig } from "../src/compactor.js";
import { parseHistoricalBlocks } from "../src/blocks.js";
import type { StoredValueAdvice } from "../src/value-advice-store.js";
import type { SessionEntryLike } from "../src/types.js";

const cases = ["simple conversation", "protected restriction", "unresolved failure", "large terminal output", "test output", "file read", "diff", "search output", "structured JSON", "repeated observations", "resource evolution", "merged episode", "activity segment", "hard-cap omitted prefix", "branch switch", "current-state conflict", "recovery marker", "isolated worker", "candidate store ready", "candidate store missing"];
function entries(label: string): SessionEntryLike[] { const user = { type: "message", id: `${label}-user`, parentId: null, message: { role: "user", content: [{ type: "text", text: label.includes("restriction") ? "Do not remove the public API." : `Handle the ${label}.` }] } } as SessionEntryLike; const assistant = { type: "message", id: `${label}-assistant`, parentId: `${label}-user`, message: { role: "assistant", content: [{ type: "text", text: label.includes("failure") ? `The ${label} remains unresolved after exit 1. `.repeat(30) : `Recorded deterministic evidence for ${label}. `.repeat(label.includes("large") ? 300 : 20) }] } } as SessionEntryLike; return [user, assistant]; }
function adviceFor(source: readonly SessionEntryLike[]): Map<string, StoredValueAdvice> { return new Map(parseHistoricalBlocks(source).map((block) => [block.id, { blockId: block.id, candidateIntegrityHash: `fixture-${block.id}`, semanticClass: block.kind === "user" ? "instruction" : "evidence", importance: "high", compressionRisk: "medium", reuseLikelihood: "medium", uniqueness: "high", action: "keep", confidence: 0.9 }])); }
test("off and shadow replay outputs are exactly equal across the value-worker matrix", async () => { const config = resolveCompactorConfig({ targetTokens: 1800, enableSemanticCompression: false }); for (const name of cases) { const source = entries(name); const off = await compactEntries(source, { config, valueWorkerMode: "off", hardOutputTokens: 2000 }); const shadow = await compactEntries(source, { config, valueWorkerMode: "shadow", valueAdvice: adviceFor(source), hardOutputTokens: 2000 }); assert.equal(shadow.summary, off.summary, name); assert.equal(shadow.renderedTokens, off.renderedTokens, name); assert.equal(shadow.targetTokens, off.targetTokens, name); assert.equal(shadow.details.generationHash, off.details.generationHash, name); assert.deepEqual(shadow.validation, off.validation, name); assert.deepEqual(shadow.plan.units.map((unit) => [unit.id, unit.selected.level, unit.selected.text, unit.sourceRefs]), off.plan.units.map((unit) => [unit.id, unit.selected.level, unit.selected.text, unit.sourceRefs]), name); } });
