import type { HistoricalBlock, SourceRef } from "./types.js";
import { compactWhitespace, estimateTokensFromText, hasRestrictionLanguage, hasUnresolvedLanguage, hashText } from "./utils.js";

export const HISTORY_VALUE_SCHEMA_VERSION = 1;
export type HistoryValueCategory = "restriction"|"goal"|"decision"|"next-action"|"blocker"|"status"|"failure"|"resource-state"|"task-episode"|"activity"|"metric"|"evidence"|"archive-range";
export type HistorySourceAuthority = "user"|"assistant"|"tool"|"project"|"derived";
export type HistoryLifecycle = "current"|"conflict"|"superseded"|"unresolved"|"resolved"|"open"|"closed"|"unknown";
export type HistoryPriority = "A"|"B"|"C"|"D"|"E";
export type HistoryEvidenceType = "exact-source"|"structured-source"|"deterministic-derived";
export type HistoryConfidence = "source-fact"|"deterministic-inference"|"heuristic-inference";
export type HistoryUniqueness = "unique"|"duplicate"|"unknown";
export interface HistoryValueRecord {
  readonly schemaVersion: 1; readonly id: string; readonly category: HistoryValueCategory; readonly sourceAuthority: HistorySourceAuthority;
  readonly lifecycle: HistoryLifecycle; readonly priority: HistoryPriority; readonly sourceRefs: readonly SourceRef[];
  readonly sourceRange: { readonly startEntryId: string; readonly endEntryId: string }; readonly sourceOrder:{readonly start:number;readonly end:number}; readonly sourceTokens: number;
  readonly renderedTokenEstimate: number; readonly evidenceType: HistoryEvidenceType; readonly uniqueness: HistoryUniqueness;
  readonly recoveryCost: number; readonly reproductionCost: number; readonly compressionRisk: number;
  readonly staticImportance: number; readonly staticSignals: readonly string[]; readonly stateKey: string;
  readonly resourceIdentity?: string; readonly taskIdentity?: string; readonly duplicateGroupIdentity?: string;
  readonly supersessionSource?: SourceRef; readonly conflictSources?: readonly SourceRef[]; readonly confidence?: HistoryConfidence;
  readonly cue?: string; readonly exactSourceRequired: boolean;
}
export interface HistoryDynamicContext { readonly retentionHints?: string; readonly recentTailTerms?: readonly string[]; readonly currentResourceIdentities?: readonly string[]; readonly openTaskIds?: readonly string[]; readonly retrievalEntryIds?: readonly string[]; readonly unresolvedFailureKeys?: readonly string[]; }
const bounded=(text:string,max=240):string=>{const clean=compactWhitespace(text).replace(/\s+/g," ");return clean.length<=max?clean:`${clean.slice(0,max-1)}…`;};
const terms=(text:string):string[]=>compactWhitespace(text).toLowerCase().match(/[a-z][a-z0-9_.:/-]{2,}/g)?.slice(0,24)??[];
function authority(block:HistoricalBlock):HistorySourceAuthority { if(block.kind==="user")return"user";if(block.kind==="tool_call"||block.kind==="tool_result"||block.kind==="bash_execution")return"tool";if(block.kind==="custom_message")return"project";return"assistant"; }
function category(block:HistoricalBlock):HistoryValueCategory {const text=block.exactText.toLowerCase(),resource=typeof block.attributes.resourceKey==="string"||typeof block.toolArguments?.path==="string";if(block.protectedExact&&hasRestrictionLanguage(block.exactText))return"restriction";if(block.isError||block.unresolved||(!/\b(no|zero)\s+(errors?|failures?)\b/.test(text)&&/\b(failed|failure|error)\b/.test(text))||(resource&&/\b(fixed|resolved|corrected)\b/.test(text)))return"failure";if(/\b(blocked|blocker|cannot continue|waiting for)\b/.test(text))return"blocker";if(/\b(next|todo|must|should)\b/.test(text)&&/\b(action|step|implement|run|fix|continue)\b/.test(text))return"next-action";if(/\b(goal|objective|purpose)\b/.test(text))return"goal";if(/\b(decided|decision|choose|selected)\b/.test(text))return"decision";if(/\b(task|implementation|work item|milestone)\b/.test(text))return"task-episode";if(block.toolName||block.attributes.resourceKey)return"resource-state";if(/\b(test|metric|tokens|bytes|milliseconds| ms\b|rss)\b/.test(text))return"metric";return block.kind==="assistant_text"?"status":"evidence";}
function identity(category:HistoryValueCategory,block:HistoricalBlock):{key:string;resource?:string;task?:string}{const resource=typeof block.attributes.resourceKey==="string"?block.attributes.resourceKey:(typeof block.toolArguments?.path==="string"?block.toolArguments.path:undefined);const tool=block.toolName??"";const sig=terms(block.exactText).slice(0,8).join("-");if(category==="resource-state")return{key:`resource:${resource??tool}:${block.kind}`,resource:resource??tool};if(category==="failure")return{key:resource||tool?`failure:${resource??tool}`:`failure:${sig}`,resource:(resource??tool)||undefined};if(category==="restriction")return{key:`restriction:${authority(block)}:${terms(block.exactText).slice(0,6).join("-")}`};if(category==="task-episode"||category==="goal"||category==="next-action")return{key:`task:${sig}`,task:sig};return{key:`${category}:${resource??sig}`,resource};}
export function createHistoryValueRecord(block:HistoricalBlock,index=0):HistoryValueRecord {const cat=category(block),auth=authority(block),idn=identity(cat,block),failure=cat==="failure",restriction=cat==="restriction",blocker=cat==="blocker",current=restriction||failure||blocker||cat==="next-action"||cat==="resource-state";const priority:HistoryPriority=restriction?"A":failure||blocker?"B":cat==="resource-state"||cat==="goal"||cat==="decision"||cat==="next-action"?"B":cat==="metric"||cat==="evidence"?"C":"D";const exactSourceRequired=restriction;const cue=restriction&&block.protectedExact?"Protected current restriction; load exact source before use.":block.kind==="tool_call"?`Tool ${block.toolName??"unknown"} call observed; complete arguments omitted.`:block.kind==="tool_result"&&!failure?`Tool ${block.toolName??"unknown"} result observed; complete output omitted.`:bounded(block.exactText);const signals=[auth,cat,...(failure?["unresolved"]:[]),...(block.protectedExact?["protected"]:[]),...(block.reproducible?["reproducible"]:[])];const resolvedFailure=failure&&!block.isError&&!block.unresolved&&/\b(fixed|resolved|corrected)\b/i.test(block.exactText),closedEpisode=cat==="task-episode"&&((block.kind==="tool_result"&&!block.isError&&/\b(test|validation)\b/i.test(block.toolName??block.exactText))||block.kind==="custom_message"&&/\bcompleted\b/i.test(block.exactText)||block.kind==="user"&&/\b(accept|approved)\b/i.test(block.exactText));const staticImportance=Math.min(100,(priority==="A"?95:priority==="B"?75:priority==="C"?50:25)+(failure?5:0));return{schemaVersion:1,id:hashText(`history-value-v1:${block.id}:${index}:${cat}`),category:cat,sourceAuthority:auth,lifecycle:failure?(resolvedFailure?"resolved":"unresolved"):cat==="task-episode"?(closedEpisode?"closed":"open"):current?"current":"unknown",priority,sourceRefs:block.sourceRefs.some(ref=>ref.entryId===block.entryId)?block.sourceRefs.filter(ref=>ref.entryId===block.entryId):[{entryId:block.entryId}],sourceRange:{startEntryId:block.entryId,endEntryId:block.entryId},sourceOrder:{start:block.entryIndex,end:block.entryIndex},sourceTokens:block.rawTokens,renderedTokenEstimate:estimateTokensFromText(cue),evidenceType:block.protectedExact?"exact-source":auth==="tool"?"structured-source":"deterministic-derived",uniqueness:"unknown",recoveryCost:block.reproducible?20:80,reproductionCost:block.reproducible?20:80,compressionRisk:block.protectedExact?100:failure?85:40,staticImportance,staticSignals:signals,stateKey:idn.key,...(idn.resource?{resourceIdentity:idn.resource}:{}),...(idn.task?{taskIdentity:idn.task}:{}),confidence:auth==="user"||auth==="tool"?"source-fact":"heuristic-inference",cue,exactSourceRequired};}
export function historyStaticValue(record:HistoryValueRecord):number{return record.staticImportance+record.compressionRisk*.15+record.recoveryCost*.1+(record.lifecycle==="unresolved"?20:0)+(record.uniqueness==="unique"?10:record.uniqueness==="duplicate"?-10:0);}
export function historyDynamicValue(record:HistoryValueRecord,context:HistoryDynamicContext={}):number {let value=historyStaticValue(record);const hay=`${context.retentionHints??""} ${(context.recentTailTerms??[]).join(" ")}`.toLowerCase(),cue=(record.cue??"").toLowerCase();if(hay&&terms(hay).some(term=>cue.includes(term)))value+=25;if(record.resourceIdentity&&context.currentResourceIdentities?.includes(record.resourceIdentity))value+=30;if(record.taskIdentity&&context.openTaskIds?.includes(record.taskIdentity))value+=30;if(context.retrievalEntryIds?.some(id=>record.sourceRefs.some(ref=>ref.entryId===id)))value+=20;if(context.unresolvedFailureKeys?.includes(record.stateKey))value+=30;return value;}
export function orderHistoryValues(records:readonly HistoryValueRecord[],context:HistoryDynamicContext={}):HistoryValueRecord[]{return [...records].sort((a,b)=>historyDynamicValue(b,context)-historyDynamicValue(a,context)||a.sourceOrder.start-b.sourceOrder.start||a.sourceRange.startEntryId.localeCompare(b.sourceRange.startEntryId)||a.id.localeCompare(b.id));}
export function extractHistoryValues(blocks:readonly HistoricalBlock[]):HistoryValueRecord[]{const seen=new Map<string,string>();return blocks.map((block,index)=>{let value=createHistoryValueRecord(block,index);const signature=`${value.category}:${value.cue??""}`;const prior=seen.get(signature);if(prior)value={...value,...(value.category==="status"?{category:"activity" as const,lifecycle:"closed" as const,stateKey:`activity:${hashText(signature)}`}:{}) ,uniqueness:"duplicate",duplicateGroupIdentity:hashText(signature)};else{seen.set(signature,value.id);value={...value,uniqueness:"unique"};}return value;});}
