import { createHash, randomBytes } from "node:crypto";
import { readFileSync } from "node:fs";
import { chmod, link, lstat, mkdir, open, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { COMPACTION_WORKER_PROTOCOL_VERSION, type WorkerJobType } from "./compaction-worker-protocol.js";

export type WorkerPriority = "high" | "low";
interface Owner { readonly schemaVersion: 1; readonly pid: number; readonly processStartIdentity: string; readonly nonce: string; readonly createdAtMs: number; readonly priority: WorkerPriority; readonly jobType: WorkerJobType; }
export interface SchedulerLease { readonly slot: number; readonly slots: number; readonly queueWaitMs: number; readonly queuePosition: number; release(): Promise<void>; }
export interface SchedulerOptions { readonly slots?: number; readonly timeoutMs?: number; readonly pollMs?: number; readonly priority: WorkerPriority; readonly jobType: WorkerJobType; readonly signal?: AbortSignal; readonly directory?: string; readonly malformedStableMs?: number; }
const START_RE=/^\d+ \([^)]*\) [A-Z] (?:\S+ ){18}(\S+)/;
export function linuxProcessStartIdentity(pid=process.pid): string | undefined { try { const text=readFileSync(`/proc/${pid}/stat`,"utf8"); return text.match(START_RE)?.[1]; } catch { return undefined; } }
function ownerAlive(owner: Owner): boolean | undefined {
  if (process.platform !== "linux") return undefined;
  try {
    const text = readFileSync(`/proc/${owner.pid}/stat`, "utf8");
    const current = text.match(START_RE)?.[1];
    return current === undefined ? undefined : current === owner.processStartIdentity;
  } catch (error) {
    return (error as NodeJS.ErrnoException).code === "ENOENT" ? false : undefined;
  }
}
export function defaultSchedulerDirectory(): string { const uid=typeof process.getuid==="function"?String(process.getuid()):"unknown";const identity=createHash("sha256").update(uid).digest("hex").slice(0,16);return join(tmpdir(),`chrono-compact-worker-v${COMPACTION_WORKER_PROTOCOL_VERSION}-${identity}`); }
async function ensureDirectory(path:string):Promise<void>{await mkdir(path,{recursive:true,mode:0o700});await chmod(path,0o700);}
async function readOwner(path:string):Promise<Owner|undefined>{try{const metadata=await lstat(path);const uid=typeof process.getuid==="function"?process.getuid():metadata.uid;if(!metadata.isFile()||metadata.isSymbolicLink()||metadata.uid!==uid||(metadata.mode&0o777)!==0o600||metadata.size<2||metadata.size>1_000)return undefined;const value=JSON.parse(await readFile(path,"utf8")) as Owner;const keys=Object.keys(value).sort().join(",");return value&&keys==="createdAtMs,jobType,nonce,pid,priority,processStartIdentity,schemaVersion"&&value.schemaVersion===1&&Number.isSafeInteger(value.pid)&&value.pid>0&&typeof value.processStartIdentity==="string"&&value.processStartIdentity.length>0&&value.processStartIdentity.length<=64&&/^[a-f0-9]{32}$/.test(value.nonce)&&Number.isSafeInteger(value.createdAtMs)&&value.createdAtMs>0&&(value.priority==="high"||value.priority==="low")&&(value.jobType==="replay-compaction"||value.jobType==="candidate-store-update"||value.jobType==="rollup-shadow")?value:undefined;}catch{return undefined;}}
const malformedArtifacts = new Map<string,{fingerprint:string;firstSeenMs:number}>();
async function removeDead(path:string,malformedStableMs:number):Promise<boolean>{const owner=await readOwner(path);if(!owner){try{const value=await lstat(path);const fingerprint=`${String(value.dev)}:${String(value.ino)}:${value.size}:${value.mtimeMs}`;const prior=malformedArtifacts.get(path);if(!prior||prior.fingerprint!==fingerprint){malformedArtifacts.set(path,{fingerprint,firstSeenMs:Date.now()});return false;}if(Date.now()-prior.firstSeenMs<malformedStableMs)return false;const again=await lstat(path);const current=`${String(again.dev)}:${String(again.ino)}:${again.size}:${again.mtimeMs}`;if(current!==fingerprint||await readOwner(path))return false;await rm(path,{force:true});malformedArtifacts.delete(path);return true;}catch{malformedArtifacts.delete(path);return false;}}malformedArtifacts.delete(path);const alive=ownerAlive(owner);if(alive===false){const again=await readOwner(path);if(again?.nonce===owner.nonce){await rm(path,{force:true});return true;}}return false;}
async function cleanup(directory:string,malformedStableMs:number):Promise<void>{for(const name of await readdir(directory)){if(!name.startsWith("ticket-")&&!name.startsWith("slot-")&&!/^\.(?:ticket|slot)-.+\.tmp$/.test(name))continue;await removeDead(join(directory,name),malformedStableMs);}}
async function publishOwner(directory:string,name:string,owner:Owner):Promise<boolean>{const finalPath=join(directory,name);const temporary=join(directory,`.${name}-${owner.nonce}.tmp`);try{const handle=await open(temporary,"wx",0o600);try{await handle.writeFile(JSON.stringify(owner));await handle.sync();}finally{await handle.close();}try{await link(temporary,finalPath);return true;}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")return false;throw error;}}finally{await rm(temporary,{force:true});}}
function wait(ms:number,signal?:AbortSignal):Promise<void>{return new Promise((resolve,reject)=>{if(signal?.aborted)return reject(new Error("worker-aborted"));const timer=setTimeout(resolve,ms);signal?.addEventListener("abort",()=>{clearTimeout(timer);reject(new Error("worker-aborted"));},{once:true});});}
function priorityValue(value:WorkerPriority):number{return value==="high"?0:1;}
export async function acquireHostWorkerSlot(options:SchedulerOptions):Promise<SchedulerLease>{
 const slots=Math.floor(options.slots??1);if(slots<1||slots>4)throw new Error("host worker slots must be from 1 through 4");const timeoutMs=Math.max(1,Math.floor(options.timeoutMs??900_000));const pollMs=Math.min(1000,Math.max(20,Math.floor(options.pollMs??75)));const malformedStableMs=Math.max(50,Math.floor(options.malformedStableMs??5_000));const directory=options.directory??defaultSchedulerDirectory();await ensureDirectory(directory);await cleanup(directory,malformedStableMs);
 const startIdentity=linuxProcessStartIdentity()??"unverified";const nonce=randomBytes(16).toString("hex");const owner:Owner={schemaVersion:1,pid:process.pid,processStartIdentity:startIdentity,nonce,createdAtMs:Date.now(),priority:options.priority,jobType:options.jobType};const ticketName=`ticket-${nonce}.json`;const ticketPath=join(directory,ticketName);if(!await publishOwner(directory,ticketName,owner))throw new Error("scheduler-ticket-collision");const started=Date.now();let maximumPosition=1;
 try{for(;;){if(options.signal?.aborted)throw new Error("worker-aborted");if(Date.now()-started>=timeoutMs)throw new Error("scheduler-timeout");await cleanup(directory,malformedStableMs);const names=(await readdir(directory)).filter(x=>x.startsWith("ticket-"));const tickets:(Owner&{name:string})[]=[];for(const name of names){const value=await readOwner(join(directory,name));if(value)tickets.push({...value,name});}tickets.sort((a,b)=>priorityValue(a.priority)-priorityValue(b.priority)||a.createdAtMs-b.createdAtMs||a.nonce.localeCompare(b.nonce));const position=Math.max(1,tickets.findIndex(x=>x.nonce===nonce)+1);maximumPosition=Math.max(maximumPosition,position);
   let available=-1;for(let slot=0;slot<slots;slot++){const path=join(directory,`slot-${slot}.json`);await removeDead(path,malformedStableMs);if(await publishOwner(directory,`slot-${slot}.json`,owner)){available=slot;break;}}
   if(available>=0){const earlier=tickets.slice(0,position-1).length;if(earlier>=slots){const path=join(directory,`slot-${available}.json`);const current=await readOwner(path);if(current?.nonce===nonce)await rm(path,{force:true});}else{await rm(ticketPath,{force:true});let released=false;return{slot:available,slots,queueWaitMs:Date.now()-started,queuePosition:maximumPosition,release:async()=>{if(released)return;released=true;const path=join(directory,`slot-${available}.json`);const current=await readOwner(path);if(current?.nonce===nonce)await rm(path,{force:true});await rm(ticketPath,{force:true});}};}}
   await wait(pollMs,options.signal);
 }}finally{await rm(ticketPath,{force:true});}
}
export async function schedulerArtifactCounts(directory=defaultSchedulerDirectory()):Promise<{tickets:number;slots:number}>{try{const names=await readdir(directory);return{tickets:names.filter(x=>x.startsWith("ticket-")).length,slots:names.filter(x=>x.startsWith("slot-")).length};}catch{return{tickets:0,slots:0};}}
