import assert from "node:assert/strict";
import { appendFile, chmod, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { cleanupHistoryRollupStore, createHistoryRollupRuntime, historyRollupStorePath, loadHistoryNode, updateHistoryRollupStore } from "../src/history-rollup-store.js";
const header={type:"session",version:3,id:"rollup-test"};
const msg=(id:string,parentId:string|null,role="assistant",text=`status ${id}`)=>({type:"message",id,parentId,message:{role,content:text,stopReason:"stop"}});
async function fixture(t:test.TestContext,count=8){const directory=await mkdtemp(join(tmpdir(),"chrono-rollup-test-"));t.after(()=>rm(directory,{recursive:true,force:true}));const sessionPath=join(directory,"session.jsonl"),entries=[];let parent:null|string=null;for(let n=0;n<count;n++){const id=`e${n}`;entries.push(msg(id,parent,n===0?"user":"assistant",n===0?"Never publish without approval.":n===3?"Blocked waiting for validation.":n===4?"build failed E42 on /repo/a.ts":`routine status ${n}`));parent=id;}await writeFile(sessionPath,[header,...entries].map(x=>JSON.stringify(x)).join("\n")+"\n",{mode:0o600});const runtime=createHistoryRollupRuntime(sessionPath,{targetLeafEntries:2,targetLeafSourceBytes:100000,targetLeafBlocks:100,nodeCacheBytes:2000});return{directory,sessionPath,entries,runtime,leaf:parent!};}
test("new build, exact hit, append, and immutable changed paths",async t=>{const f=await fixture(t),first=await updateHistoryRollupStore(f.runtime,f.leaf);assert.equal(first.transition,"new");assert.ok(first.leafNodesCreated>=4);const manifestPath=join(historyRollupStorePath(f.sessionPath),"manifest.json"),manifestBefore=await readFile(manifestPath),mtime=(await stat(manifestPath)).mtimeMs,branch=f.runtime.branchManifest!,sealed=branch.leafNodes.filter(x=>x.sealed),sealedBytes=await Promise.all(sealed.map(x=>readFile(join(f.runtime.directory,"nodes",`${x.nodeId}.json`))));const exact=await updateHistoryRollupStore(f.runtime,f.leaf);assert.equal(exact.transition,"exact-hit");assert.equal(exact.nodesCreated,0);assert.equal((await stat(manifestPath)).mtimeMs,mtime);assert.deepEqual(await readFile(manifestPath),manifestBefore);const next=msg("e8",f.leaf,"assistant","next action implement validation");await appendFile(f.sessionPath,`${JSON.stringify(next)}\n`);const appended=await updateHistoryRollupStore(f.runtime,"e8");assert.ok(appended.transition==="append"||appended.transition==="append-open-leaf");assert.ok(appended.entriesParsed<=3);assert.ok(appended.nodesCreated>0);assert.equal(f.runtime.branchManifest!.leafNodes.reduce((n,x)=>n+x.entryCount,0),f.runtime.branchManifest!.sourceBranchEntryCount);for(let i=0;i<sealed.length;i++)assert.deepEqual(await readFile(join(f.runtime.directory,"nodes",`${sealed[i]!.nodeId}.json`)),sealedBytes[i]);});
test("branch switch reuses verified common leaves and excludes abandoned tail",async t=>{const f=await fixture(t,7);await updateHistoryRollupStore(f.runtime,f.leaf);const left=msg("left",f.leaf,"assistant","left abandoned secret marker");await appendFile(f.sessionPath,`${JSON.stringify(left)}\n`);await updateHistoryRollupStore(f.runtime,"left");const common=f.entries[4]!.id,right=msg("right",common,"assistant","right active state");await appendFile(f.sessionPath,`${JSON.stringify(right)}\n`);const switched=await updateHistoryRollupStore(f.runtime,"right");assert.equal(switched.transition,"branch-switch-reuse");assert.ok(switched.nodesReused>0);const branch=f.runtime.branchManifest!;assert.equal(branch.branchLeafId,"right");for(const descriptor of branch.leafNodes){const text=await readFile(join(f.runtime.directory,"nodes",`${descriptor.nodeId}.json`),"utf8");assert.doesNotMatch(text,/left abandoned secret marker/);}});
test("one writer, cancellation, integrity, permissions, and byte cache fail safely",async t=>{const f=await fixture(t,6);await updateHistoryRollupStore(f.runtime,f.leaf);const before=await readFile(join(f.runtime.directory,"manifest.json"));const lock=join(f.runtime.directory,"writer.lock"),proc=await readFile(`/proc/${process.pid}/stat`,"utf8"),start=proc.slice(proc.lastIndexOf(")")+2).split(" ")[19];await writeFile(lock,JSON.stringify({pid:process.pid,start}),{mode:0o600});await assert.rejects(()=>updateHistoryRollupStore(f.runtime,f.leaf),/busy/);await rm(lock);const controller=new AbortController();controller.abort();await assert.rejects(()=>updateHistoryRollupStore(f.runtime,f.leaf,{signal:controller.signal}),/aborted/);assert.deepEqual(await readFile(join(f.runtime.directory,"manifest.json")),before);assert.equal((await stat(f.runtime.directory)).mode&0o777,0o700);for(const file of await readdir(join(f.runtime.directory,"nodes")))assert.equal((await stat(join(f.runtime.directory,"nodes",file))).mode&0o777,0o600);const ids=f.runtime.branchManifest!.leafNodes.map(x=>x.nodeId);for(const id of ids)await loadHistoryNode(f.runtime,id);assert.ok(f.runtime.cacheBytes<=f.runtime.config.nodeCacheBytes||f.runtime.cache.size===1);assert.ok(f.runtime.cacheEvictions>0);const corrupt=ids[0]!;await writeFile(join(f.runtime.directory,"nodes",`${corrupt}.json`),"{}\n");f.runtime.cache.delete(corrupt);await assert.rejects(()=>loadHistoryNode(f.runtime,corrupt),/corrupt/);const manifest=JSON.parse(before.toString());assert.equal(JSON.stringify(manifest).includes(f.sessionPath),false);});
test("open-leaf overflow seals complete coverage across repeated appends",async t=>{const f=await fixture(t,1),runtime=createHistoryRollupRuntime(f.sessionPath,{targetLeafEntries:100,targetLeafSourceBytes:350,targetLeafBlocks:100});await updateHistoryRollupStore(runtime,f.leaf);let parent=f.leaf;for(let n=1;n<=8;n++){const id=`append-${n}`;await appendFile(f.sessionPath,`${JSON.stringify(msg(id,parent,"assistant",`routine appended state ${n} ${"x".repeat(80)}`))}\n`);parent=id;await updateHistoryRollupStore(runtime,parent);const branch=runtime.branchManifest!;assert.equal(branch.leafNodes.reduce((sum,x)=>sum+x.entryCount,0),branch.sourceBranchEntryCount);assert.equal(branch.leafNodes.filter(x=>!x.sealed).length<=1,true);}});
test("manifest corruption rebuilds safely and cleanup preserves retained branch nodes",async t=>{const f=await fixture(t,6);await updateHistoryRollupStore(f.runtime,f.leaf);await writeFile(join(f.runtime.directory,"manifest.json"),"{}\n");const rebuilt=await updateHistoryRollupStore(f.runtime,f.leaf);assert.equal(rebuilt.transition,"manifest-corruption");const live=new Set([...f.runtime.branchManifest!.leafNodes.map(x=>x.nodeId),...f.runtime.branchManifest!.levels.flat()]);await writeFile(join(f.runtime.directory,"nodes","orphan.json"),"orphan\n",{mode:0o600});const cleaned=await cleanupHistoryRollupStore(f.runtime);assert.ok(cleaned.nodesRemoved>=1);for(const id of live)await stat(join(f.runtime.directory,"nodes",`${id}.json`));});
test("source truncation and configuration changes rebuild derived state",async t=>{const f=await fixture(t,6);await updateHistoryRollupStore(f.runtime,f.leaf);await writeFile(f.sessionPath,[header,...f.entries.slice(0,3)].map(x=>JSON.stringify(x)).join("\n")+"\n",{mode:0o600});const truncated=await updateHistoryRollupStore(f.runtime,"e2");assert.equal(truncated.transition,"source-truncation");const changed=createHistoryRollupRuntime(f.sessionPath,{targetLeafEntries:3});const configured=await updateHistoryRollupStore(changed,"e2");assert.equal(configured.transition,"configuration-change");assert.equal(changed.branchManifest!.sourceBranchEntryCount,3);});
test("large entry remains one leaf and node files omit complete source",async t=>{const f=await fixture(t,1),sentinel="FULL_TOOL_RESULT_SENTINEL_"+"x".repeat(200000),entry={type:"message",id:"huge",parentId:f.leaf,message:{role:"toolResult",toolCallId:"call",toolName:"read",content:[{type:"text",text:sentinel}],isError:false}};await appendFile(f.sessionPath,`${JSON.stringify(entry)}\n`);await updateHistoryRollupStore(f.runtime,"huge");const descriptor=f.runtime.branchManifest!.leafNodes.at(-1)!,text=await readFile(join(f.runtime.directory,"nodes",`${descriptor.nodeId}.json`),"utf8");assert.doesNotMatch(text,/FULL_TOOL_RESULT_SENTINEL_/);assert.ok(descriptor.sourceBytes>100000);});
