import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { renderHistoryRollupPrototype, validateHistoryRollupPrototype } from "../src/history-rollup-renderer.js";
import { createHistoryRollupRuntime, updateHistoryRollupStore } from "../src/history-rollup-store.js";
const msg=(id:string,parentId:string|null,role:string,text:string)=>({type:"message",id,parentId,message:{role,content:text,stopReason:"stop"}});
async function fixture(t:test.TestContext,count=30){const directory=await mkdtemp(join(tmpdir(),"chrono-rollup-render-"));t.after(()=>rm(directory,{recursive:true,force:true}));const sessionPath=join(directory,"session.jsonl"),entries=[],header={type:"session",version:3,id:"render"};let parent:null|string=null;for(let n=0;n<count;n++){const id=`r${n}`,text=n===0?`Never publish without explicit approval. ${"restriction-detail ".repeat(300)}`:n===2?"Goal: preserve branch-aware state.":n===4?"Blocked waiting for validation.":n===6?"Next action: run exact reference checks.":n===8?"build failed E99 and remains unresolved.":n===10?"Decision: use immutable nodes.":`routine event ${n}`;entries.push(msg(id,parent,n===0?"user":"assistant",text));parent=id;}await writeFile(sessionPath,[header,...entries].map(value=>JSON.stringify(value)).join("\n")+"\n",{mode:0o600});const runtime=createHistoryRollupRuntime(sessionPath,{targetLeafEntries:3,targetLeafSourceBytes:100000,targetLeafBlocks:100});await updateHistoryRollupStore(runtime,parent!);runtime.cache.clear();runtime.cacheBytes=0;runtime.nodesLoaded=0;runtime.nodeBytesRead=0;return{runtime,ledger:runtime.ledger!,leaf:parent!};}
test("prototype renders four bounded sections with exact restriction and recovery",async t=>{const f=await fixture(t),result=await renderHistoryRollupPrototype(f.runtime,f.ledger,{targetTokens:20000,hardTokens:25000});for(const heading of ["# CURRENT WORK","# RECENT EVENTS","# SELECTED OLDER EVIDENCE","# ARCHIVE MAP"])assert.match(result.text,new RegExp(heading));assert.match(result.text,/Never publish without explicit approval/);assert.match(result.text,/Exact source: history_get\("r0"/);assert.equal(result.quality.currentRestrictionCount,1);assert.equal(result.quality.exactCurrentRestrictions,1);assert.equal(result.quality.restrictionCueCoverage,1);assert.equal(result.quality.invalidSourceReferences,0);assert.equal(result.quality.falseCompletions,0);assert.equal(result.validation.ok,true,result.validation.issues.join(","));assert.ok(result.quality.outputTokens<=25000);assert.equal(result.quality.lossyRecords,result.quality.lossyRecordsWithRecovery);});
test("long restriction becomes one complete recovery cue and lines are never cut",async t=>{const f=await fixture(t,5),record=f.runtime.branchManifest!.leafNodes[0];assert.ok(record);const result=await renderHistoryRollupPrototype(f.runtime,f.ledger,{targetTokens:1000,hardTokens:1000,currentTokens:128});assert.match(result.text,/recovery-only current restriction/);assert.match(result.text,/history_get\("r0"\)/);assert.ok(result.text.split("\n").every(line=>!line.endsWith("…")));assert.ok(result.quality.outputTokens<=1000);});
test("renderer reads root plus bounded recent leaves, not all old leaves",async t=>{const f=await fixture(t,120),leafCount=f.runtime.branchManifest!.leafNodes.length,result=await renderHistoryRollupPrototype(f.runtime,f.ledger,{targetTokens:5000,dynamicContext:{retentionHints:"immutable nodes",recentTailTerms:["validation"],retrievalEntryIds:["r10"]}});assert.ok(leafCount>20);assert.ok(result.quality.nodesReadDuringRender<=64);assert.ok(result.quality.nodeBytesReadDuringRender<16*1024*1024);assert.equal(result.validation.ok,true);});
test("validator rejects bad references, missing recovery, false completion, and hard overflow",async t=>{const f=await fixture(t,10),bad={schemaVersion:2,id:"bad",category:"failure",sourceAuthority:"derived",lifecycle:"unresolved",priority:"B",sourceRefs:[{entryId:"missing"}],sourceRange:{startEntryId:"missing",endEntryId:"missing"},sourceOrder:{start:0,end:0},sourceTokens:1,renderedTokenEstimate:1,evidenceType:"deterministic-derived",uniqueness:"unique",recoveryCost:1,reproductionCost:1,compressionRisk:1,staticImportance:1,staticSignals:[],stateKey:"failure:x",normalizedClaimHash:"bad",relations:[],confidence:"deterministic-inference",cue:"failure completed",exactSourceRequired:false} as const,result=validateHistoryRollupPrototype("[heuristic reduced failure unresolved; omitted detail] failure completed\n[source fact] unsupported\ncut…\n"+"x".repeat(10000),f.ledger,[bad],10);assert.equal(result.ok,false);assert.ok(result.issues.some(x=>x.startsWith("invalid-source")));assert.ok(result.issues.includes("loss-without-recovery"));assert.ok(result.issues.includes("false-completion"));assert.ok(result.issues.includes("hard-token-limit"));assert.ok(result.issues.includes("cut-line"));assert.ok(result.issues.includes("unsupported-exact-fact"));});
