import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createCandidateSegmentStore, type CandidateSegmentDescriptor } from "../src/candidate-segment-store.js";
import type { CandidatePrecomputeRecord } from "../src/candidates.js";
import { classifyProviderFailure, actualCostMicroUsd, upperBoundCostMicroUsd, usdToMicroUsd, type ValueModelCall } from "../src/value-worker-model.js";
import { runValueWorker } from "../src/value-worker.js";
import { acquireValueModelSlot } from "../src/value-worker-scheduler.js";
import { boundedValueWorkerBatch } from "../src/value-worker-prompt.js";
import { DEFAULT_VALUE_WORKER_SETTINGS, type ValueWorkerSettings } from "../src/value-worker-types.js";
import { loadStoredAdvice, readValueAdviceManifest, resetAdviceCircuit, valueAdviceStorePath } from "../src/value-advice-store.js";

const model = { id: "fake", name: "Fake", provider: "test", api: "openai-completions", baseUrl: "http://invalid.local", reasoning: true, input: ["text"], cost: { input: 2, output: 4, cacheRead: 1, cacheWrite: 3 }, contextWindow: 100_000, maxTokens: 4_000 } as any;
const context = { model, thinkingLevel: "low", modelRegistry: { find: (provider: string, id: string) => provider === "test" && id === "fake" ? model : undefined, hasConfiguredAuth: () => true } } as any;
const settings = (patch: Partial<ValueWorkerSettings> = {}): ValueWorkerSettings => ({ ...DEFAULT_VALUE_WORKER_SETTINGS, mode: "shadow", model: "main", maxInputTokensPerSession: 100_000, maxOutputTokensPerSession: 100_000, ...patch });
const candidate = (id = "block"): CandidatePrecomputeRecord => ({ blockId: id, key: id, dependency: "source-local", integrityHash: `integrity-${id}`, blockKind: "assistant_text", isError: false, unresolved: false, reproducible: true, identifierCount: 0, candidates: [{ id: `${id}:reduced`, level: "reduced", text: "bounded assistant evidence", tokens: 6, rawTokens: 20, utility: 1, lossy: true, reducer: "generic-text", reducerVersion: "1", omissions: [], sourceRefs: [{ entryId: "private" }], metadata: { blockKind: "assistant_text" } }] });
async function fixture(records = [candidate()]) { const root = await mkdtemp(join(tmpdir(), "chrono-value-controls-")); const sessionPath = join(root, "session.jsonl"); const store = createCandidateSegmentStore(sessionPath); const descriptor: CandidateSegmentDescriptor = { sequence: 1, fileName: "segment.json", sourceStartByte: 0, sourceEndByte: 1, firstSourceLine: 1, lastSourceLine: 1, sourceEntryCount: 1, sourceBlockCount: records.length, persistentCandidateRecordCount: records.length, segmentByteSize: 1, segmentContentHash: "segment-hash", firstSourceEntryId: "first", lastSourceEntryId: "last", safeBoundary: true }; store.cache.set(descriptor.fileName, { bytes: 1, records }); store.manifest = { schemaVersion: 1, sourceFileIdentity: { deviceId: "1", inodeId: "1" }, sourceSessionIdentity: "anonymous", sourceLedgerSchemaVersion: 1, sourceLedgerIntegrityState: "valid", sourceBytePositionCovered: 1, sourceLinePositionCovered: 1, sourceEntryCountCovered: 1, candidateConfigHash: "config", reducerVersionHash: "reducers", segmentTargets: { sourceBytes: 1, sourceEntries: 1, candidateRecords: 1 }, segments: [descriptor], openPairEntryIds: [], manifestGeneration: 1, lastTransition: "new", createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString(), manifestIntegrityHash: "candidate-manifest" }; return { root, store, advicePath: valueAdviceStorePath(sessionPath) }; }
const answer = (prompt: string, usage = { input: 10, output: 5, cacheRead: 2, cacheWrite: 1, totalTokens: 18, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } }) => { const itemId = [...prompt.matchAll(/"itemId":"([^"]+)"/g)].at(-1)?.[1] ?? "missing"; return { role: "assistant", content: [{ type: "text", text: JSON.stringify({ version: 1, items: [{ itemId, semanticClass: "evidence", importance: "high", compressionRisk: "medium", reuseLikelihood: "medium", uniqueness: "high", action: "keep", confidence: 0.9 }] }) }], api: "openai-completions", provider: "test", model: "fake", usage, stopReason: "stop", timestamp: Date.now() } as any; };

test("structured provider failures classify without raw-message matching", () => { assert.deepEqual(classifyProviderFailure({ status: 429 }), { status: "provider-rate-limit", transient: true }); assert.deepEqual(classifyProviderFailure({ code: "ECONNRESET" }), { status: "provider-temporary-failure", transient: true }); assert.equal(classifyProviderFailure(new Error("429" as string)).transient, false); });
test("micro-USD conversion and price boundaries are integer and upward rounded", () => { assert.equal(usdToMicroUsd(0.000001), 1); assert.equal(usdToMicroUsd(0.0000011), 2); assert.equal(upperBoundCostMicroUsd(model, 10, 5), 40); assert.equal(actualCostMicroUsd(model, { input: 10, output: 5, cacheRead: 2, cacheWrite: 1, totalTokens: 18, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } }), 45); });
test("transient retry uses deterministic backoff and persists attempts", async () => { const f = await fixture(); try { let calls = 0; const sleeps: number[] = []; const call: ValueModelCall = { call: async (_m, prompt) => { calls++; if (calls === 1) throw Object.assign(new Error("hidden"), { status: 503 }); return answer(prompt); } }; const result = await runValueWorker({ ctx: context, settings: settings(), store: f.store, modelCall: call, schedulerDirectory: join(f.root, "scheduler"), sleep: async (ms) => { sleeps.push(ms); } }); assert.equal(result.status, "shadow-complete"); assert.equal(calls, 2); assert.deepEqual(sleeps, [250]); assert.equal((await readValueAdviceManifest(f.advicePath))?.usage.calls, 2); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("authentication failure is not retried and does not count against the circuit", async () => { const f = await fixture(); try { let calls = 0; const call: ValueModelCall = { call: async () => { calls++; throw Object.assign(new Error("hidden"), { status: 401 }); } }; const result = await runValueWorker({ ctx: context, settings: settings({ circuitFailureLimit: 1 }), store: f.store, modelCall: call, schedulerDirectory: join(f.root, "scheduler") }); assert.equal(result.status, "model-auth-unavailable"); assert.equal(calls, 1); assert.equal((await readValueAdviceManifest(f.advicePath))?.circuitState, "closed"); assert.equal((await readValueAdviceManifest(f.advicePath))?.consecutiveFailures, 0); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("failed attempts reserve bounded tokens and cost before a retry", async () => { const f = await fixture(); try { let calls = 0; const batch = boundedValueWorkerBatch([candidate()], 40, 6000, 1500); const oneAttemptCost = upperBoundCostMicroUsd(model, batch.inputTokens, 1500)!; const result = await runValueWorker({ ctx: context, settings: settings({ retries: 2, maxOutputTokensPerSession: 2000, maxEstimatedCostMicroUsd: oneAttemptCost * 2 }), store: f.store, modelCall: { call: async () => { calls++; throw Object.assign(new Error("hidden"), { status: 503 }); } }, schedulerDirectory: join(f.root, "scheduler"), sleep: async () => {} }); assert.equal(result.status, "budget-exhausted"); assert.equal(calls, 1); const manifest = await readValueAdviceManifest(f.advicePath); assert.equal(manifest?.usage.outputTokens, 1500); assert.equal(manifest?.usage.costMicroUsd, oneAttemptCost); assert.equal(manifest?.consecutiveFailures, 0); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("cancellation during a provider call does not count against the circuit", async () => { const f = await fixture(); try { const controller = new AbortController(); const result = await runValueWorker({ ctx: context, settings: settings({ circuitFailureLimit: 1 }), store: f.store, modelCall: { call: async () => { controller.abort(); throw Object.assign(new Error("hidden"), { name: "AbortError" }); } }, schedulerDirectory: join(f.root, "scheduler"), signal: controller.signal }); assert.equal(result.status, "cancelled"); assert.equal((await readValueAdviceManifest(f.advicePath))?.consecutiveFailures, 0); assert.equal((await readValueAdviceManifest(f.advicePath))?.circuitState, "closed"); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("cancellation after a response preserves the prior manifest before publication", async () => { const f = await fixture(); try { const controller = new AbortController(); const result = await runValueWorker({ ctx: context, settings: settings(), store: f.store, modelCall: { call: async (_m, prompt) => { controller.abort(); return answer(prompt); } }, schedulerDirectory: join(f.root, "scheduler"), signal: controller.signal }); assert.equal(result.status, "cancelled"); assert.equal((await readValueAdviceManifest(f.advicePath))?.processedSegmentIdentities.length, 0); assert.equal((await readValueAdviceManifest(f.advicePath))?.adviceFiles.length, 0); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("one repair call succeeds and contains no original item list", async () => { const f = await fixture(); try { const prompts: string[] = []; const call: ValueModelCall = { call: async (_m, prompt) => { prompts.push(prompt); if (prompts.length === 1) return { ...answer(prompt), content: [{ type: "text", text: "not json" }] } as any; return answer(prompts[0]!); } }; const result = await runValueWorker({ ctx: context, settings: settings(), store: f.store, modelCall: call, schedulerDirectory: join(f.root, "scheduler") }); assert.equal(result.status, "shadow-complete"); assert.equal(result.usage.repairCalls, 1); assert.equal(prompts.length, 2); assert.ok(!prompts[1]!.includes("bounded assistant evidence")); assert.ok(!prompts[1]!.includes("candidate-manifest")); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("exact monetary boundary passes and one micro-USD below blocks", async () => { const batch = boundedValueWorkerBatch([candidate()], 40, 6000, 1500); const boundary = upperBoundCostMicroUsd(model, batch.inputTokens, 1500)!; for (const [limit, expected] of [[boundary, "shadow-complete"], [boundary - 1, "budget-exhausted"]] as const) { const f = await fixture(); try { let calls = 0; const result = await runValueWorker({ ctx: context, settings: settings({ maxEstimatedCostMicroUsd: limit }), store: f.store, modelCall: { call: async (_m, prompt) => { calls++; return answer(prompt); } }, schedulerDirectory: join(f.root, "scheduler") }); assert.equal(result.status, expected); assert.equal(calls, expected === "shadow-complete" ? 1 : 0); } finally { await rm(f.root, { recursive: true, force: true }); } } });
test("persisted call budget survives a new runtime", async () => { const f = await fixture(); try { const call: ValueModelCall = { call: async (_m, prompt) => answer(prompt) }; const configured = settings({ maxCallsPerSession: 1 }); assert.equal((await runValueWorker({ ctx: context, settings: configured, store: f.store, modelCall: call, schedulerDirectory: join(f.root, "s1") })).status, "shadow-complete"); f.store.manifest = { ...f.store.manifest!, segments: [{ ...f.store.manifest!.segments[0]!, segmentContentHash: "new-segment" }], manifestIntegrityHash: "candidate-manifest" }; f.store.cache.set("segment.json", { bytes: 1, records: [candidate("next")] }); assert.equal((await runValueWorker({ ctx: context, settings: configured, store: f.store, modelCall: call, schedulerDirectory: join(f.root, "s2") })).status, "budget-exhausted"); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("open circuit persists, blocks, then one half-open success closes it", async () => { const f = await fixture(); try { let clock = 1_000_000; const configured = settings({ circuitFailureLimit: 1, circuitCooldownSeconds: 30 }); await runValueWorker({ ctx: context, settings: configured, store: f.store, modelCall: { call: async () => { throw Object.assign(new Error("hidden"), { status: 503 }); } }, schedulerDirectory: join(f.root, "fail"), sleep: async () => {}, now: () => clock }); let calls = 0; assert.equal((await runValueWorker({ ctx: context, settings: configured, store: f.store, modelCall: { call: async (_m, prompt) => { calls++; return answer(prompt); } }, schedulerDirectory: join(f.root, "blocked"), now: () => clock })).status, "circuit-open"); assert.equal(calls, 0); clock += 31_000; assert.equal((await runValueWorker({ ctx: context, settings: configured, store: f.store, modelCall: { call: async (_m, prompt) => { calls++; return answer(prompt); } }, schedulerDirectory: join(f.root, "half"), now: () => clock })).status, "shadow-complete"); assert.equal(calls, 1); assert.equal((await readValueAdviceManifest(f.advicePath))?.circuitState, "closed"); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("manual circuit reset preserves advice descriptors", async () => { const f = await fixture(); try { await runValueWorker({ ctx: context, settings: settings(), store: f.store, modelCall: { call: async (_m, prompt) => answer(prompt) }, schedulerDirectory: join(f.root, "scheduler") }); const before = await readValueAdviceManifest(f.advicePath); assert.equal(await resetAdviceCircuit(f.advicePath), true); const after = await readValueAdviceManifest(f.advicePath); assert.deepEqual(after?.adviceFiles, before?.adviceFiles); assert.equal(after?.circuitState, "closed"); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("exact hit rewrites no manifest and preserves old model advice", async () => { const f = await fixture(); try { let calls = 0; const call: ValueModelCall = { call: async (_m, prompt) => { calls++; return answer(prompt); } }; const main = settings(); await runValueWorker({ ctx: context, settings: main, store: f.store, modelCall: call, schedulerDirectory: join(f.root, "main") }); const manifestPath = join(f.advicePath, "manifest.json"); const before = (await stat(manifestPath)).mtimeMs; await new Promise((resolve) => setTimeout(resolve, 5)); assert.equal((await runValueWorker({ ctx: context, settings: main, store: f.store, modelCall: call, schedulerDirectory: join(f.root, "hit") })).status, "no-pending-segments"); assert.equal((await stat(manifestPath)).mtimeMs, before); const alternate = settings({ model: "test/fake" }); assert.equal((await runValueWorker({ ctx: context, settings: alternate, store: f.store, modelCall: call, schedulerDirectory: join(f.root, "alternate") })).status, "shadow-complete"); const beforeReturn = calls; assert.equal((await runValueWorker({ ctx: context, settings: main, store: f.store, modelCall: call, schedulerDirectory: join(f.root, "return") })).status, "no-pending-segments"); assert.equal(calls, beforeReturn); assert.equal((await readValueAdviceManifest(f.advicePath))?.adviceFiles.length, 2); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("a corrupt manifest rebuilds verified descriptors and preserves the hard session budget", async () => { const f = await fixture(); try { let calls = 0; const call: ValueModelCall = { call: async (_m, prompt) => { calls++; return answer(prompt); } }; const configured = settings({ maxCallsPerSession: 1 }); await runValueWorker({ ctx: context, settings: configured, store: f.store, modelCall: call, schedulerDirectory: join(f.root, "first") }); await writeFile(join(f.advicePath, "manifest.json"), "{}\n", { mode: 0o600 }); f.store.manifest = { ...f.store.manifest!, segments: [{ ...f.store.manifest!.segments[0]!, segmentContentHash: "new-segment" }], manifestIntegrityHash: "new-candidate-manifest" }; f.store.cache.set("segment.json", { bytes: 1, records: [candidate("next")] }); const result = await runValueWorker({ ctx: context, settings: configured, store: f.store, modelCall: call, schedulerDirectory: join(f.root, "second") }); assert.equal(result.status, "budget-exhausted"); assert.equal(calls, 1); const rebuilt = await readValueAdviceManifest(f.advicePath); assert.equal(rebuilt?.usage.calls, 1); assert.equal(rebuilt?.adviceFiles.length, 1); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("model scheduler enforces slot limits 1, 2, and 4 and supports timeout and cancellation", async () => { for (const slots of [1, 2, 4]) { const root = await mkdtemp(join(tmpdir(), `chrono-slots-${slots}-`)); try { const held = await Promise.all(Array.from({ length: slots }, () => acquireValueModelSlot({ slots, timeoutMs: 1000, directory: root }))); assert.equal((await readdir(root)).filter((x) => x.startsWith("slot-")).length, slots); await assert.rejects(acquireValueModelSlot({ slots, timeoutMs: 20, directory: root }), /scheduler-timeout/); const controller = new AbortController(); const waiting = acquireValueModelSlot({ slots, timeoutMs: 1000, directory: root, signal: controller.signal }); controller.abort(); await assert.rejects(waiting, /cancelled/); await Promise.all(held.map((x) => x.release())); assert.deepEqual(await readdir(root).catch(() => []), []); } finally { await rm(root, { recursive: true, force: true }); } } });
test("one corrupt advice file and one stale record fail independently", async () => { const f = await fixture(); try { await runValueWorker({ ctx: context, settings: settings(), store: f.store, modelCall: { call: async (_m, prompt) => answer(prompt) }, schedulerDirectory: join(f.root, "scheduler") }); const manifest = (await readValueAdviceManifest(f.advicePath))!; assert.equal((await loadStoredAdvice(f.advicePath, manifest, new Map([["block", "wrong"]]))).size, 0); await writeFile(join(f.advicePath, "advice", manifest.adviceFiles[0]!.fileName), "{}\n", { mode: 0o600 }); assert.equal((await loadStoredAdvice(f.advicePath, manifest, new Map([["block", "integrity-block"]]))).size, 0); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("one active run per session rejects a concurrent value job", async () => { const f = await fixture(); try { let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); let started!: () => void; const active = new Promise<void>((resolve) => { started = resolve; }); const first = runValueWorker({ ctx: context, settings: settings(), store: f.store, modelCall: { call: async (_m, prompt) => { started(); await gate; return answer(prompt); } }, schedulerDirectory: join(f.root, "scheduler") }); await active; const second = await runValueWorker({ ctx: context, settings: settings(), store: f.store, modelCall: { call: async (_m, prompt) => answer(prompt) }, schedulerDirectory: join(f.root, "scheduler") }); assert.equal(second.status, "advice-store-busy"); release(); assert.equal((await first).status, "shadow-complete"); } finally { await rm(f.root, { recursive: true, force: true }); } });
test("advice files persist normalized advice without prompt or response", async () => { const f = await fixture(); try { await runValueWorker({ ctx: context, settings: settings(), store: f.store, modelCall: { call: async (_m, prompt) => answer(prompt) }, schedulerDirectory: join(f.root, "scheduler") }); const manifest = await readValueAdviceManifest(f.advicePath); const bytes = await readFile(join(f.advicePath, "advice", manifest!.adviceFiles[0]!.fileName), "utf8"); assert.ok(!bytes.includes("bounded assistant evidence")); assert.ok(!bytes.includes("itemId")); assert.ok(bytes.includes("candidateIntegrityHash")); } finally { await rm(f.root, { recursive: true, force: true }); } });
